### ISSUE TITLE
Remove August Data from the reports

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#17]
Hi Jakub,

The August data looks funny in the reports for a couple of reasons:
1. We started collecting data late in the month so the open jobs average isn't reflective of what was actually happening that month.
2. All open jobs were treated as new jobs because they were all loaded into the system that month. 

Can we remove the August information from our charts without deleting the data? If this isn't your department, please hand it off to Maxim. Thanks!

**Comment by johnnyoshika** [comment]
Reassigned to @ma-gu.

@ryanstgermaine: is it enough to restrict the datepicker range so that a date before Sept 1 can't be selected?

@ma-gu: I think the easiest way to achieve this is to hard code the the `startAt` value to `2015-09-01` for the `reports/range` endpoint:
https://github.com/bcjobs/analytics/issues/36#issuecomment-162926517
...but let's wait to get confirmation from @ryanstgermaine on whether this is enough.

**Comment by ryanstgermaine** [comment]
Hi @ma-gu 

I think that does the trick. As long as the report doesn't show August, it works for me :).

**Comment by ma-gu** [comment]
Done.

**Comment by johnnyoshika** [comment]
Thank you @ma-gu.

@ryanstgermaine: this will be rolled out once this pull request gets accepted, https://github.com/bcjobs/analytics/pull/59, and Jakub updates the app to use the date range api endpoint...so probably early this coming week.
