### ISSUE TITLE
CSV Downloads

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#36]
Create downloadable reports for each of these sections with a full list of all. The reports should be accessible by creating a button at the bottom of each report that says "download". They should only be able to download if they are logged in.

![2016-02-12_1605](https://cloud.githubusercontent.com/assets/6778782/13023957/38c39a94-d1a3-11e5-8da9-ae5d6a99dff2.png)

![skills](https://cloud.githubusercontent.com/assets/6778782/13023958/3b7e55a8-d1a3-11e5-8a75-0d89753f2ad2.png)

![by_open_jobs](https://cloud.githubusercontent.com/assets/6778782/13023959/3eb74fe0-d1a3-11e5-891c-cc3c9e1fefe6.png)

![year_to_date_comapies](https://cloud.githubusercontent.com/assets/6778782/13023960/417a2d7e-d1a3-11e5-9b35-ee513f589e08.png)

**Comment by ryanstgermaine** [comment]
Create downloadable reports for each of these sections with a full list of all.
![2016-02-12_1605](https://cloud.githubusercontent.com/assets/6778782/13023943/126b4086-d1a3-11e5-9c38-c56926d05c4b.png)

![skills](https://cloud.githubusercontent.com/assets/6778782/13023947/1c1667aa-d1a3-11e5-90d4-3373165c62e2.png)

**Comment by johnnyoshika** [comment]
@ma-gu: Can you please create API endpoints that will return CSV files for these reports?  Ryan is looking for the exact same data as shown above, except the full set instead of limiting to just 20 records.

Taking this as an example:
![image](https://cloud.githubusercontent.com/assets/504505/13025119/8df55f04-d1b5-11e5-9f54-80d741b3b9d7.png)

Let's use our standard naming conventions as much as possible.

```
GET /api/v1.0/downloads/trendingOpenJobTitles
```

Column names from here:
![image](https://cloud.githubusercontent.com/assets/504505/13025149/5880e504-d1b6-11e5-9b15-9ac926f9fb7c.png)

| name | current | previous | companies | averageAge |
| --- | :-: | --: | --: | --: |
| Software Developer | 60 | 50 | 30 | 30 |
| Senior Software Developer | 60 | 50 | 30 | 30 |
| Front End Developer | 60 | 50 | 30 | 30 |

```
Filename: analytics-trendingOpenJobTitles-at-2016-02-11.csv
```

Please also secure these endpoints so that only logged in users (but no roles required) can access them.

**Comment by ma-gu** [comment]
Here is some notes about implementation:
1. I have added 2 necessary parameters(date and type of report) similar to our reporting endpoint api/v1.0/reports/trends: 
   `GET /api/v1.0/downloads/trendingOpenJobTitles?at=2016-01-27&type=Software`
2. As we have 2 types of reports then I was forced to modify filename to the following pattern(in order to reflect both report and trend type):
   `Filename: analytics-trendingOpenJobTitles-for-Software-at-2016-01-27.csv`

I have checked report (for Software type) after modification with diff compare tool and it's exactly the same as before (it looks like a good idea to such checking cause I have refactored TrendsBuilder).

**Comment by johnnyoshika** [comment]
@ma-gu:

1) Looks good to me.
2) Filename change makes sense.

**Comment by johnnyoshika** [comment]
@ma-gu: I've changed the endpoint name from `downloads` to `exports` to better reflect your controller name: https://github.com/bcjobs/analytics/commit/3d202da56aaa94eb12acf99dcf4aafc7553d785a

**Comment by ma-gu** [comment]
@johnnyoshika: Sure, make sense.

**Comment by johnnyoshika** [comment]
@ma-gu: it looks like there was a mix-up and 2 of the downloads that were created aren't the ones that Ryan requested.  Can you add the 2 missing downloads?

**Comment by johnnyoshika** [comment]
@LoganHollins: Please implement the UI for the download.  The original requirement is listed at the top of this issue by Ryan.

Here are the endpoints that you'll want to hit.  A simple `href` to the URL will trigger the file download:
https://github.com/bcjobs/analytics/blob/dev/BCJobs.Analytics.Web/Controllers/ExportController.cs

Feel free to ask Michelle to style the download button if you'd like.  Alternatively, you can use Bootstrap's buttons: http://getbootstrap.com/css/#buttons
